package cfg

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// configLocations returns the ordered list of config file paths to check.
// AA_CONFIG_PATH env var takes highest priority.
func configLocations() []string {
	var locs []string
	if p := os.Getenv("AA_CONFIG_PATH"); p != "" {
		locs = append(locs, p)
	}
	locs = append(locs, "/etc/agentauth/config")
	home, err := os.UserHomeDir()
	if err == nil {
		locs = append(locs, filepath.Join(home, ".agentauth", "config"))
	}
	return locs
}

// loadConfigFile searches config file locations in priority order and
// returns the mode, admin secret, and resolved path. Returns empty
// strings if no config file is found.
func loadConfigFile() (mode, adminSecret, path string) {
	for _, loc := range configLocations() {
		m, s, p := loadConfigFileAt(loc)
		if p != "" {
			return m, s, p
		}
	}
	return "", "", ""
}

// loadConfigFileAt reads a single config file and extracts MODE and
// ADMIN_SECRET values. Returns empty strings if the file doesn't exist
// or can't be read.
func loadConfigFileAt(path string) (mode, adminSecret, resolvedPath string) {
	f, err := os.Open(path)
	if err != nil {
		return "", "", ""
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch strings.TrimSpace(key) {
		case "MODE":
			mode = strings.TrimSpace(value)
		case "ADMIN_SECRET":
			adminSecret = strings.TrimSpace(value)
		}
	}
	return mode, adminSecret, path
}

// WriteConfigFile writes a config file at the given path with the
// specified mode and admin secret value. Creates parent directories
// with 0700 permissions. The file is written with 0600 permissions.
func WriteConfigFile(path, mode, adminSecretValue string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	content := fmt.Sprintf("# AgentAuth Configuration\n# Generated by: aactl init --mode=%s\n# Generated at: %s\n\nMODE=%s\nADMIN_SECRET=%s\n",
		mode,
		time.Now().UTC().Format(time.RFC3339),
		mode,
		adminSecretValue,
	)

	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("write config file: %w", err)
	}
	return nil
}
