// SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0

package cfg

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/devonartis/agentwrit/internal/obs"
)

// configLocations returns the ordered list of config file paths to check.
// AA_CONFIG_PATH env var takes highest priority.
func configLocations() []string {
	var locs []string
	if p := os.Getenv("AA_CONFIG_PATH"); p != "" {
		locs = append(locs, p)
	}
	locs = append(locs, "/etc/broker/config")
	home, err := os.UserHomeDir()
	if err == nil {
		locs = append(locs, filepath.Join(home, ".broker", "config"))
	}
	return locs
}

// loadConfigFile searches config file locations in priority order and
// returns the mode, admin secret, and resolved path. Returns empty
// strings if no config file is found.
func loadConfigFile() (mode, adminSecret, path string) {
	for _, loc := range configLocations() {
		m, s, p := loadConfigFileAt(loc)
		if p != "" {
			return m, s, p
		}
	}
	return "", "", ""
}

// loadConfigFileAt reads a single config file and extracts MODE and
// ADMIN_SECRET values. Returns empty strings if the file doesn't exist
// or can't be read.
func loadConfigFileAt(path string) (mode, adminSecret, resolvedPath string) {
	// Reject symlinks to prevent path traversal attacks.
	if info, err := os.Lstat(path); err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			obs.Warn("CFG", "configfile", "config path is a symlink, skipping",
				"path="+path)
			return "", "", ""
		}
	}

	f, err := os.Open(path)
	if err != nil {
		return "", "", ""
	}
	defer f.Close()

	// Reject config file with insecure permissions (SSH/GPG convention).
	if info, err := f.Stat(); err == nil {
		perm := info.Mode().Perm()
		if perm&0077 != 0 {
			obs.Warn("CFG", "configfile", "config file has insecure permissions, skipping",
				fmt.Sprintf("path=%s perms=%04o expected=0600", path, perm))
			return "", "", ""
		}
	}

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch strings.TrimSpace(key) {
		case "MODE":
			mode = strings.TrimSpace(value)
		case "ADMIN_SECRET":
			adminSecret = strings.TrimSpace(value)
		}
	}
	return mode, adminSecret, path
}

// WriteConfigFile writes a config file at the given path with the
// specified mode and admin secret value. Creates parent directories
// with 0700 permissions. Uses O_EXCL for atomic create-or-fail.
// Set force=true to overwrite an existing file (rejects symlinks).
func WriteConfigFile(path, mode, adminSecretValue string, force bool) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	// Reject symlinks even in force mode.
	if info, err := os.Lstat(path); err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("config path is a symlink: %s", path)
		}
	}

	content := fmt.Sprintf("# Broker Configuration\n# Generated by: awrit init --mode=%s\n# Generated at: %s\n\nMODE=%s\nADMIN_SECRET=%s\n",
		mode,
		time.Now().UTC().Format(time.RFC3339),
		mode,
		adminSecretValue,
	)

	flags := os.O_WRONLY | os.O_CREATE | os.O_EXCL
	if force {
		flags = os.O_WRONLY | os.O_CREATE | os.O_TRUNC
	}

	f, err := os.OpenFile(path, flags, 0600)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("config file already exists at %s. Use --force to overwrite", path)
		}
		return fmt.Errorf("write config file: %w", err)
	}
	defer f.Close()

	if _, err := f.WriteString(content); err != nil {
		return fmt.Errorf("write config content: %w", err)
	}
	return nil
}
